<?php

namespace AppBundle\Repository;

/**
 * RewiewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewiewRepository extends \Doctrine\ORM\EntityRepository
{
}
